[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "genesis.json" }]
optimizer = true
optimizer_runs = 1000000
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
# https://book.getfoundry.sh/reference/config/formatter#line_length
[fmt]
line_length = 100
tab_width = 4
func_attrs_with_params_multiline = true
ignore = ["lib/**"]
